sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: xenial
language: python
python:
    # python versions used in el7 SCL & supported fedora
    - "3.6"
    - "3.7"
env:
  matrix:
    - DJANGO_MAX=2.2.100 DB=postgres TEST=pulp
    #- DJANGO_MAX=2.2.100 TEST=docs
matrix:
  fast_finish: true
addons:
    # postgres versions provided by el7 RHSCL (lowest supportable version)
    postgresql: "9.6"
services:
    - postgresql
    - redis-server
install: source .travis/install.sh
before_script: source .travis/before_script.sh
script: source .travis/script.sh

stages:
  - name: test
  - name: deploy
    if: tag IS present
  - name: publish-beta-docs
    if: tag IS present
  - name: publish-nightly-docs
jobs:
  include:
  - stage: deploy
    script: skip
    deploy:
      provider: pypi
      distributions: sdist bdist_wheel
      user: pulp
      password:
        secure: uc/2uwF2M01bA+JDoKEExyYVgZZPu9uv7X63DPzFVbCOgaa8slgkH1kvCmEPFPy6M3IXf0YitQUDbKN5E5gQ7vlbGaMPlqrQXxkW5OlaUOYmBGkuT8MPtAAhqA/hUxhYlweEYpZSzsDwEk0C+UPsiZXbVytpS9ikMaP6WflSl7PQIi5P/luS6U3pRmVa/oHf+2qiTRgoy0F0MIBOotEqSeaTv4c/2mDvns9mgNa4Y0yz+uUL/a0QVICz8+M9pK3eY+oXcYtt4LTF62sKp6ICLuyOdOaU85IKiexrLRSofjezqOBTatLLb8Tu5rKeuv5q6VUUyBPq8ZO8rIpCSsnEK90s1dCJLNQoyHy5G93WT3xDFrWtoBAk5vDCNSaKloTjSsCFhfaPcLRDnLsrjdMSi9cD+TJFb6uTaVPUyYh5Hl83MiOSnzIS0UWvBW45K1cR/TzofTFGaABrI8UyUreRv9700o05OGJBrmDNvbSo7Yy1FjDHrdSbUXnwoCh9E7Nr3093bvw6hxCdYoYCDMhnEESJ+RTcH9ymiNGq0djT06TkEMm25O54vdDzGsdAMaouD+rx6Q/7Z5bNFnJ4GrdKqPI7/0wRrQpN4+MrdF7+uVHgCNgatIBf2Mqp9a7ybM1Zf5O6K35y1Zpkr6u69vt4qhFi4ndfgvI9/uC/t+Q3yxU=
      on:
        tags: true
  - stage: publish-beta-docs
    script: bash .travis/publish_docs.sh beta
    env:
      - DJANGO_MAX=2.2.100
      - DB=postgres
      - TEST=docs
    if: tag =~ ^pulpcore-plugin-3.0*
  - stage: publish-nightly-docs
    script: bash .travis/publish_docs.sh nightly
    env:
      - DJANGO_MAX=2.2.100
      - DB=postgres
      - TEST=docs
    if: type != pull_request
